# Generated by Django 3.1 on 2020-10-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0009_add_order_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordertoken",
            name="cancelled",
            field=models.BooleanField(default=False, verbose_name="cancelled"),
        ),
        migrations.AlterField(
            model_name="ordertoken",
            name="token",
            field=models.CharField(
                blank=True, default="", max_length=64, verbose_name="token"
            ),
            preserve_default=False,
        ),
    ]
