# Generated by Django 3.1 on 2020-10-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0012_add_storage_on_ice_product"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="additionalproduct", name="optional_services_per_period",
        ),
        migrations.AddConstraint(
            model_name="additionalproduct",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    service__in=[
                        "dinghy_place",
                        "parking_permit",
                        "storage_on_ice",
                        "summer_storage_for_docking_equipment",
                        "summer_storage_for_trailers",
                    ]
                ),
                fields=("service", "period"),
                name="optional_services_per_period",
            ),
        ),
    ]
