# Generated by Django 3.1 on 2020-10-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0013_replace_enum_constraint_for_string"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_type",
            field=models.CharField(
                choices=[
                    ("lease_order", "Lease order"),
                    ("additional_product_order", "Additional product order"),
                ],
                default="lease_order",
                max_length=30,
                verbose_name="order type",
            ),
        ),
    ]
