# Generated by Django 3.1 on 2020-11-03 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0014_add_order_type"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="order",
            name="unique_lease",
        ),
    ]
