# Generated by Django 3.1 on 2021-01-14 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0018_add_price_tiers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderlogentry",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="log_entries",
                to="payments.order",
                verbose_name="order",
            ),
        ),
    ]
