# Generated by Django 3.1 on 2021-01-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0019_auto_20210114_1227"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="customer_phone",
            field=models.TextField(blank=True, null=True),
        ),
    ]
