# Generated by Django 3.1 on 2021-03-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0022_add_offer_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "Waiting"),
                    ("rejected", "Rejected"),
                    ("cancelled", "Cancelled"),
                    ("expired", "Expired"),
                    ("error", "Error"),
                    ("paid", "Paid"),
                    ("paid_man", "Paid manually"),
                    ("refunded", "Refunded"),
                ],
                default="waiting",
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="orderlogentry",
            name="from_status",
            field=models.CharField(
                choices=[
                    ("waiting", "Waiting"),
                    ("rejected", "Rejected"),
                    ("cancelled", "Cancelled"),
                    ("expired", "Expired"),
                    ("error", "Error"),
                    ("paid", "Paid"),
                    ("paid_man", "Paid manually"),
                    ("refunded", "Refunded"),
                ],
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="orderlogentry",
            name="to_status",
            field=models.CharField(
                choices=[
                    ("waiting", "Waiting"),
                    ("rejected", "Rejected"),
                    ("cancelled", "Cancelled"),
                    ("expired", "Expired"),
                    ("error", "Error"),
                    ("paid", "Paid"),
                    ("paid_man", "Paid manually"),
                    ("refunded", "Refunded"),
                ],
                max_length=9,
            ),
        ),
    ]
