# Generated by Django 3.1 on 2021-04-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0028_update_order_statuses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="due_date",
            field=models.DateField(blank=True, null=True, verbose_name="due date"),
        ),
    ]
