# Generated by Django 3.1.7 on 2021-05-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0029_update_order_due_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="berthproduct",
            options={"ordering": ["min_width", "pricing_category"]},
        ),
        migrations.RemoveConstraint(
            model_name="berthproduct",
            name="unique_width_range",
        ),
        migrations.AddField(
            model_name="berthproduct",
            name="pricing_category",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Default"),
                    (1, "Dinghy places"),
                    (2, "Trailer places"),
                    (3, "Vasikkasaari berths"),
                ],
                default=0,
                verbose_name="pricing category",
            ),
        ),
        migrations.AddConstraint(
            model_name="berthproduct",
            constraint=models.UniqueConstraint(
                fields=("min_width", "max_width", "pricing_category"),
                name="unique_width_range",
            ),
        ),
    ]
