# Generated by Django 3.2.8 on 2021-11-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0030_add_berth_pricing_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="additionalproduct",
            name="talpa_ecom_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="talpa eCom product id"
            ),
        ),
        migrations.AddField(
            model_name="berthproduct",
            name="talpa_ecom_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="talpa eCom product id"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="talpa_ecom_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="talpa eCom order id"
            ),
        ),
        migrations.AddField(
            model_name="winterstorageproduct",
            name="talpa_ecom_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="talpa eCom product id"
            ),
        ),
    ]
