# Generated by Django 3.2.8 on 2021-11-23 12:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0031_talpa_product_accounting"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="talpaproductaccounting",
            name="talpa_ecom_accounting_id",
        ),
        migrations.AlterField(
            model_name="talpaproductaccounting",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
