# Generated by Django 3.2.12 on 2022-05-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0033_remove_duplicated_talpa_order_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_notification_sent",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="payment notification sent"
            ),
        ),
    ]
