# Generated by Django 3.2.25 on 2024-08-26 10:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0034_order_payment_notification_sent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="additionalproduct",
            name="tax_percentage",
            field=models.DecimalField(
                choices=[
                    (Decimal("25.50"), "25.50"),
                    (Decimal("24.00"), "24.00"),
                    (Decimal("14.00"), "14.00"),
                    (Decimal("10.00"), "10.00"),
                ],
                decimal_places=2,
                default=Decimal("25.50"),
                max_digits=5,
                verbose_name="tax percentage",
            ),
        ),
        migrations.AlterField(
            model_name="berthproduct",
            name="tax_percentage",
            field=models.DecimalField(
                choices=[(Decimal("25.50"), "25.50"), (Decimal("24.00"), "24.00")],
                decimal_places=2,
                default=Decimal("25.50"),
                max_digits=5,
                verbose_name="tax percentage",
            ),
        ),
        migrations.AlterField(
            model_name="winterstorageproduct",
            name="tax_percentage",
            field=models.DecimalField(
                choices=[(Decimal("25.50"), "25.50"), (Decimal("24.00"), "24.00")],
                decimal_places=2,
                default=Decimal("25.50"),
                max_digits=5,
                verbose_name="tax percentage",
            ),
        ),
    ]
