# Generated by Django 2.2.3 on 2019-10-16 08:12

import uuid

from django.db import migrations, models
from django.db.models import Q


def populate_default_uuids(apps, schema_editor):
    User = apps.get_model("users", "User")

    for u in User.objects.filter(Q(uuid__isnull=True)):
        u.uuid = uuid.uuid4()
        u.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("helusers", "0001_add_ad_groups"),
        ("users", "0002_change_db_table_name"),
    ]

    operations = [
        migrations.AlterModelOptions(name="user", options={"ordering": ("id",)}),
        migrations.AddField(
            model_name="user",
            name="ad_groups",
            field=models.ManyToManyField(blank=True, to="helusers.ADGroup"),
        ),
        migrations.AddField(
            model_name="user",
            name="department_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunPython(populate_default_uuids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="user", name="uuid", field=models.UUIDField(unique=True)
        ),
    ]
