# Generated by Django 2.1.2 on 2019-04-17 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0006_reservation_application_code"),
        ("applications", "0006_add_berth_switch"),
    ]

    operations = []
