# Generated by Django 2.2.6 on 2020-01-27 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("harbors", "0012_disable_reverse_from_municipality"),
        ("leases", "0001_initial"),
        ("applications", "0014_update_verbose_names"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BerthReservation", new_name="BerthApplication",
        ),
        migrations.RenameModel(
            old_name="WinterStorageReservation", new_name="WinterStorageApplication",
        ),
        migrations.AlterModelOptions(
            name="berthapplication",
            options={
                "permissions": (
                    ("resend_application", "Can resend confirmation for applications"),
                )
            },
        ),
        migrations.AlterModelOptions(
            name="winterstorageapplication",
            options={
                "permissions": (
                    ("resend_application", "Can resend confirmation for applications"),
                )
            },
        ),
        migrations.RenameField(
            model_name="harborchoice", old_name="reservation", new_name="application",
        ),
        migrations.RenameField(
            model_name="winterstorageareachoice",
            old_name="reservation",
            new_name="application",
        ),
        migrations.AlterUniqueTogether(
            name="harborchoice", unique_together={("application", "priority")},
        ),
        migrations.AlterUniqueTogether(
            name="winterstorageareachoice",
            unique_together={("application", "priority")},
        ),
    ]
