# Generated by Django 2.2.6 on 2020-01-28 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0015_rename_reservations_to_applications"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="berthswitchreasontranslation",
            table="applications_berthswitchreason_translation",
        ),
    ]
