# Generated by Django 2.2.6 on 2020-02-06 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0004_change_boat_weight_to_int"),
        ("applications", "0016_change_berthswitchreasontranslation_model_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="berthapplication",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="berth_applications",
                to="customers.CustomerProfile",
            ),
        ),
    ]
