# Generated by Django 2.2.6 on 2020-02-25 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0018_add_status_to_applications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="berthapplication",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="berth_applications",
                to="customers.CustomerProfile",
            ),
        ),
    ]
