# Generated by Django 2.2.6 on 2020-02-25 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0019_make_customer_blankable"),
    ]

    operations = [
        migrations.RemoveField(model_name="berthapplication", name="is_processed",),
        migrations.RemoveField(
            model_name="winterstorageapplication", name="is_processed",
        ),
    ]
