# Generated by Django 2.2.6 on 2020-06-23 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0012_add_boat_certificates"),
        ("applications", "0020_delete_is_processed_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="winterstorageapplication",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="winter_storage_applications",
                to="customers.CustomerProfile",
            ),
        ),
    ]
