# Generated by Django 2.2.6 on 2020-06-30 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0021_add_customer_to_winter_storage_application"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="harborchoice",
            options={"ordering": ("application", "priority")},
        ),
        migrations.AlterModelOptions(
            name="winterstorageareachoice",
            options={"ordering": ("application", "priority")},
        ),
    ]
