# Generated by Django 3.1 on 2020-08-24 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0023_update_translation_foreign_keys"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="berthapplication",
            name="data",
        ),
        migrations.RemoveField(
            model_name="winterstorageapplication",
            name="data",
        ),
    ]
