# Generated by Django 3.1 on 2020-09-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0024_remove_data_json_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="winterstorageapplication",
            name="area_type",
            field=models.CharField(
                choices=[("marked", "Marked"), ("unmarked", "Unmarked")],
                max_length=30,
                null=True,
                verbose_name="application area type",
            ),
        ),
    ]
