# Generated by Django 3.1 on 2021-03-25 07:07

from django.db import migrations, models
import django.db.models.deletion


def berth_switch_save_servicemap_id(apps, schema_editor):
    BerthSwitch = apps.get_model("applications", "BerthSwitch")

    for switch in BerthSwitch.objects.all():
        if hasattr(switch, "_temp_servicemap_id"):
            switch._temp_servicemap_id = switch.harbor.servicemap_id
            switch.save()


def berth_switch_clear_harbor_id(apps, schema_editor):
    BerthSwitch = apps.get_model("applications", "BerthSwitch")

    for switch in BerthSwitch.objects.all():
        if hasattr(switch, "_temp_servicemap_id"):
            switch.harbor = None
            switch.save()


def berth_switch_populate_harbor_from_servicemap_id(apps, schema_editor):
    BerthSwitch = apps.get_model("applications", "BerthSwitch")
    Harbor = apps.get_model("resources", "Harbor")

    for switch in BerthSwitch.objects.all():
        if hasattr(switch, "_temp_servicemap_id"):
            switch.harbor = Harbor.objects.filter(
                servicemap_id=switch._temp_servicemap_id
            ).first()
            switch.save()


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0027_remove_no_suitable_berth_notified_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="berthswitch",
            name="_temp_servicemap_id",
            field=models.CharField(null=True, blank=True, max_length=8),
        ),
        migrations.RunPython(
            berth_switch_save_servicemap_id, reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="berthswitch",
            name="harbor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="resources.harbor",
                blank=True,
                null=True,
            ),
        ),
        migrations.RunPython(
            berth_switch_clear_harbor_id, reverse_code=migrations.RunPython.noop
        ),
        migrations.RemoveField(model_name="berthswitch", name="harbor",),
        migrations.AddField(
            model_name="berthswitch",
            name="harbor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="resources.harbor",
                blank=True,
                null=True,
            ),
        ),
        migrations.RunPython(
            berth_switch_populate_harbor_from_servicemap_id,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="berthswitch",
            name="harbor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="resources.harbor",
            ),
        ),
        migrations.RemoveField(model_name="berthswitch", name="_temp_servicemap_id",),
    ]
