# Generated by Django 3.1.7 on 2021-04-15 12:42

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0027_remove_no_suitable_berth_notified_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="berthapplication",
            name="boat_draught",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="boat draught",
            ),
        ),
        migrations.AlterField(
            model_name="berthapplication",
            name="boat_length",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="boat length",
            ),
        ),
        migrations.AlterField(
            model_name="berthapplication",
            name="boat_weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="boat weight",
            ),
        ),
        migrations.AlterField(
            model_name="berthapplication",
            name="boat_width",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="boat width",
            ),
        ),
        migrations.AlterField(
            model_name="winterstorageapplication",
            name="boat_length",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="boat length",
            ),
        ),
        migrations.AlterField(
            model_name="winterstorageapplication",
            name="boat_width",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="boat width",
            ),
        ),
    ]
