# Generated by Django 3.1 on 2021-03-25 08:10

from django.db import migrations, models
import django.db.models.deletion

old_harbor_mapping = {
    1: "40393",
    2: "41636",
    3: "40971",
    4: "39913",
    5: "41390",
    6: "40672",
    7: "41926",
    8: "40166",
    9: "40827",
    10: "48272",
    11: "40310",
    12: "41189",
    13: "39950",
    14: "40864",
    15: "40290",
    16: "41454",
    17: "41066",
    18: "40948",
    19: "45995",
    20: "40359",
    21: "42225",
    22: "40712",
    23: "41359",
    24: "40590",
    25: "41669",
    26: "41150",
    27: "40842",
    28: "40897",
    29: "40800",
    30: "41074",
    31: "40203",
    32: "40535",
    33: "40627",
    34: "41857",
    35: "40876",
    36: "42276",
    37: "41472",
    38: "42136",
    39: "41415",
    40: "41637",
    41: "42130",
    42: "48272",
    43: "41189",
    44: "40359",
    45: "41359",
    46: "40393",
    47: "40864",
    48: "40864",
    49: "41454",
    50: "40971",
    51: "41472",
    52: "41390",
}


def copy_harbor_choices(apps, schema_editor):
    HarborChoice = apps.get_model("applications", "HarborChoice")
    TmpHarborChoice = apps.get_model("applications", "TmpHarborChoice")
    Harbor = apps.get_model("resources", "Harbor")

    for choice in HarborChoice.objects.all():
        TmpHarborChoice.objects.create(
            id=choice.id,
            priority=choice.priority,
            harbor=Harbor.objects.filter(
                servicemap_id=old_harbor_mapping[choice.harbor_id]
            ).first(),
            application=choice.application,
        )


def restore_harbor_choices(apps, schema_editor):
    TmpHarborChoice = apps.get_model("applications", "TmpHarborChoice")
    HarborChoice = apps.get_model("applications", "HarborChoice")

    for choice in HarborChoice.objects.all():
        choice.harbor = TmpHarborChoice.objects.get(id=choice.id).harbor
        choice.save()


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0027_map_harbors_with_resources"),
        ("applications", "0028_replace_berth_switch_harbor_with_resources"),
    ]

    operations = [
        # Create a temporary through model
        migrations.CreateModel(
            name="TmpHarborChoice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("priority", models.PositiveSmallIntegerField(verbose_name="priority")),
                (
                    "harbor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resources.Harbor",
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.BerthApplication",
                        blank=True,
                        null=True,
                    ),
                ),
            ],
        ),
        # Create the relation through the temporary model
        migrations.AddField(
            model_name="berthapplication",
            name="tmp_chosen_harbors",
            field=models.ManyToManyField(
                blank=True,
                through="applications.TmpHarborChoice",
                to="resources.Harbor",
                verbose_name="chosen harbors",
            ),
        ),
        # Copy the data to the new through field
        migrations.RunPython(
            copy_harbor_choices, reverse_code=migrations.RunPython.noop
        ),
        # Hard reset for HarborChoice.harbor
        migrations.RemoveField(model_name="harborchoice", name="harbor"),
        migrations.AddField(
            model_name="harborchoice",
            name="harbor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="resources.harbor",
                null=True,
                blank=True,
            ),
        ),
        # Replace the correct values for HarborChoice.harbor
        migrations.RunPython(
            restore_harbor_choices, reverse_code=migrations.RunPython.noop
        ),
        # Add the non-null constraint for HarborChoice.harbor
        migrations.AlterField(
            model_name="harborchoice",
            name="harbor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="resources.harbor",
            ),
        ),
        # Point the BerthApplication to the right choice model
        migrations.AlterField(
            model_name="berthapplication",
            name="chosen_harbors",
            field=models.ManyToManyField(
                blank=True,
                through="applications.HarborChoice",
                to="resources.Harbor",
                verbose_name="chosen harbors",
            ),
        ),
        # Drop the old through model and field
        migrations.DeleteModel(name="TmpHarborChoice"),
        migrations.RemoveField(
            model_name="berthapplication", name="tmp_chosen_harbors",
        ),
    ]
