# Generated by Django 3.1 on 2021-03-25 11:47

from django.db import migrations, models
import django.db.models.deletion


def copy_area_choices(apps, schema_editor):
    WinterStorageAreaChoice = apps.get_model("applications", "WinterStorageAreaChoice")
    TmpChoice = apps.get_model("applications", "TmpChoice")
    WinterStorageArea = apps.get_model("resources", "WinterStorageArea")

    for choice in WinterStorageAreaChoice.objects.all():
        TmpChoice.objects.create(
            id=choice.id,
            priority=choice.priority,
            winter_storage_area=choice.winter_storage_area.resources_area,
            application=choice.application,
        )


def restore_area_choices(apps, schema_editor):
    TmpChoice = apps.get_model("applications", "TmpChoice")
    WinterStorageAreaChoice = apps.get_model("applications", "WinterStorageAreaChoice")

    for choice in WinterStorageAreaChoice.objects.all():
        choice.winter_storage_area = TmpChoice.objects.get(
            id=choice.id
        ).winter_storage_area
        choice.save()


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0027_map_harbors_with_resources"),
        ("applications", "0030_change_boat_type_to_resources"),
    ]

    operations = [
        # Create a temporary through model
        migrations.CreateModel(
            name="TmpChoice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("priority", models.PositiveSmallIntegerField(verbose_name="priority")),
                (
                    "winter_storage_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resources.WinterStorageArea",
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.WinterStorageApplication",
                        blank=True,
                        null=True,
                    ),
                ),
            ],
        ),
        # Create the relation through the temporary model
        migrations.AddField(
            model_name="winterstorageapplication",
            name="tmp_chosen_areas",
            field=models.ManyToManyField(
                blank=True,
                through="applications.TmpChoice",
                to="resources.WinterStorageArea",
                verbose_name="chosen harbors",
            ),
        ),
        # Copy the data to the new through field
        migrations.RunPython(copy_area_choices, reverse_code=migrations.RunPython.noop),
        # Hard reset for WinterStorageAreaChoice.winter_storage_area
        migrations.RemoveField(
            model_name="winterstorageareachoice", name="winter_storage_area"
        ),
        migrations.AddField(
            model_name="winterstorageareachoice",
            name="winter_storage_area",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="resources.WinterStorageArea",
                null=True,
                blank=True,
            ),
        ),
        # Replace the correct values for WinterStorageAreaChoice.winter_storage_area
        migrations.RunPython(
            restore_area_choices, reverse_code=migrations.RunPython.noop
        ),
        # Add the non-null constraint for WinterStorageAreaChoice.winter_storage_area
        migrations.AlterField(
            model_name="winterstorageareachoice",
            name="winter_storage_area",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="resources.WinterStorageArea",
            ),
        ),
        # Point the WinterStorageApplication to the right choice model
        migrations.AlterField(
            model_name="winterstorageapplication",
            name="chosen_areas",
            field=models.ManyToManyField(
                blank=True,
                through="applications.WinterStorageAreaChoice",
                to="resources.WinterStorageArea",
                verbose_name="chosen winter storage areas",
            ),
        ),
        # Drop the old through model and field
        migrations.DeleteModel(name="TmpChoice"),
        migrations.RemoveField(
            model_name="winterstorageapplication", name="tmp_chosen_areas",
        ),
    ]
