# Generated by Django 3.1 on 2021-03-29 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0031_replace_winterstorageareachoice_area_with_resources"),
    ]

    operations = [
        migrations.AlterField(
            model_name="berthapplication",
            name="berth_switch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="applications.berthswitch",
                verbose_name="berth switch",
            ),
        ),
    ]
