# Generated by Django 3.1.7 on 2021-06-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0034_replace_berthswitch_harbor_for_berth"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="berthapplication",
            options={
                "ordering": ("-priority", "created_at"),
                "permissions": (
                    ("resend_application", "Can resend confirmation for applications"),
                ),
            },
        ),
        migrations.AlterModelOptions(
            name="winterstorageapplication",
            options={
                "ordering": ("-priority", "created_at"),
                "permissions": (
                    ("resend_application", "Can resend confirmation for applications"),
                ),
            },
        ),
        migrations.AddField(
            model_name="berthapplication",
            name="priority",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Low"), (1, "Medium"), (2, "High")],
                default=1,
                verbose_name="priority",
            ),
        ),
        migrations.AddField(
            model_name="winterstorageapplication",
            name="priority",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Low"), (1, "Medium"), (2, "High")],
                default=1,
                verbose_name="priority",
            ),
        ),
    ]
