# Generated by Django 3.1.7 on 2021-06-21 18:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0035_add_application_priority"),
    ]

    operations = [
        migrations.CreateModel(
            name="WinterStorageApplicationChange",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="time modified"),
                ),
                ("change_list", models.TextField(verbose_name="change list")),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changes",
                        to="applications.winterstorageapplication",
                    ),
                ),
            ],
            options={"ordering": ("created_at", "change_list"), "abstract": False,},
        ),
        migrations.CreateModel(
            name="BerthApplicationChange",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="time modified"),
                ),
                ("change_list", models.TextField(verbose_name="change list")),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changes",
                        to="applications.berthapplication",
                    ),
                ),
            ],
            options={"ordering": ("created_at", "change_list"), "abstract": False,},
        ),
    ]
