# Generated by Django 3.2.8 on 2021-11-11 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0015_add_customer_user_relatedname"),
        ("applications", "0037_add_application_boat_relation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="berthapplication",
            name="boat_length",
        ),
        migrations.RemoveField(
            model_name="berthapplication",
            name="boat_model",
        ),
        migrations.RemoveField(
            model_name="berthapplication",
            name="boat_name",
        ),
        migrations.RemoveField(
            model_name="berthapplication",
            name="boat_registration_number",
        ),
        migrations.RemoveField(
            model_name="berthapplication",
            name="boat_type",
        ),
        migrations.RemoveField(
            model_name="berthapplication",
            name="boat_width",
        ),
        migrations.RemoveField(
            model_name="berthapplication",
            name="boat_propulsion",
        ),
        migrations.RemoveField(
            model_name="berthapplication",
            name="boat_hull_material",
        ),
        migrations.RemoveField(
            model_name="berthapplication",
            name="boat_intended_use",
        ),
        migrations.RemoveField(
            model_name="winterstorageapplication",
            name="boat_length",
        ),
        migrations.RemoveField(
            model_name="winterstorageapplication",
            name="boat_model",
        ),
        migrations.RemoveField(
            model_name="winterstorageapplication",
            name="boat_name",
        ),
        migrations.RemoveField(
            model_name="winterstorageapplication",
            name="boat_registration_number",
        ),
        migrations.RemoveField(
            model_name="winterstorageapplication",
            name="boat_type",
        ),
        migrations.RemoveField(
            model_name="winterstorageapplication",
            name="boat_width",
        ),
        migrations.RemoveField(
            model_name="berthapplication",
            name="boat_draught",
        ),
        migrations.RemoveField(
            model_name="berthapplication",
            name="boat_is_inspected",
        ),
        migrations.RemoveField(
            model_name="berthapplication",
            name="boat_is_insured",
        ),
        migrations.RemoveField(
            model_name="berthapplication",
            name="boat_weight",
        ),
        migrations.AlterField(
            model_name="winterstorageapplication",
            name="area_type",
            field=models.CharField(
                blank=True,
                choices=[("marked", "Marked"), ("unmarked", "Unmarked")],
                max_length=30,
                null=True,
                verbose_name="application area type",
            ),
        ),
        migrations.AlterField(
            model_name="berthapplication",
            name="boat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="customers.boat",
                verbose_name="boat",
            ),
        ),
        migrations.AlterField(
            model_name="winterstorageapplication",
            name="boat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="customers.boat",
                verbose_name="boat",
            ),
        ),
    ]
