# Mandatory include
include:
  - project: 'city-of-helsinki/kuva/ci-cd-config/ci-configuration'
    ref: v2
    file: '/.gitlab-ci-template.yml'

# These variables are available for all stages
variables:
  APP_MIGRATE_COMMAND: /app/.prod/on_deploy.sh
  #APP_INITIALIZE_COMMAND: /app/.prod/on_initialize.sh
  SERVICE_PORT: "8000"

# Build stage must be included and it must extend .build.
build:
  extends: .build

review:
  # These variables are available only for review env and are merged with the general variables defined above.
  variables:
    APP_INITIALIZE_COMMAND: /app/.prod/on_initialize.sh
    K8S_SECRET_ALLOWED_HOSTS: "*"
    K8S_SECRET_DEBUG: 1
    K8S_SECRET_CREATE_SUPERUSER: 1
    K8S_SECRET_CHECK_MIGRATIONS: 1
    K8S_SECRET_SECRET_KEY: "$GL_TEST_DJANGO_SECRET_KEY"
    K8S_SECRET_TOKEN_AUTH_AUTHSERVER_URL: "https://tunnistamo.test.kuva.hel.ninja/openid"
    K8S_SECRET_CORS_ORIGIN_ALLOW_ALL: 1
    K8S_SECRET_VENE_UI_RETURN_URL: "https://venepaikat.hel.ninja/"
    K8S_SECRET_VENE_PAYMENTS_BAMBORA_API_URL: "https://real-bambora-api-url/api"
    K8S_SECRET_VENE_PAYMENTS_BAMBORA_API_KEY: "dummy-key"
    K8S_SECRET_VENE_PAYMENTS_BAMBORA_API_SECRET: "dummy-secret"
    K8S_SECRET_VENE_PAYMENTS_BAMBORA_PAYMENT_METHODS: "dummy-bank"
    K8S_SECRET_PROFILE_API_URL: "https://profiili-api.test.kuva.hel.ninja/graphql/"
    K8S_SECRET_VISMASIGN_API_URL: "$GL_TEST_VISMASIGN_API_URL"
    K8S_SECRET_VISMASIGN_CLIENT_IDENTIFIER: "$GL_TEST_VISMASIGN_CLIENT_IDENTIFIER"
    K8S_SECRET_VISMASIGN_SECRET: "$GL_TEST_VISMASIGN_SECRET"
    K8S_SECRET_ENABLE_PROFILING_TOOLS: 0

staging:
  variables:
    K8S_SECRET_TIER: "stage"
    K8S_SECRET_SKIP_DATABASE_CHECK: 1
    K8S_SECRET_ALLOWED_HOSTS: "*"
    K8S_SECRET_CORS_ORIGIN_ALLOW_ALL: 1
    K8S_SECRET_SECRET_KEY: "$GL_QA_DJANGO_SECRET_KEY"
    K8S_SECRET_TOKEN_AUTH_AUTHSERVER_URL: "https://api.hel.fi/sso-test/openid"
    K8S_SECRET_MAIL_MAILGUN_KEY: "$GL_QA_SECRET_MAILGUN_API_KEY"
    K8S_SECRET_MAIL_MAILGUN_DOMAIN: "mail.hel.ninja"
    K8S_SECRET_MAIL_MAILGUN_API: "https://api.eu.mailgun.net/v3"
    K8S_SECRET_MAILER_EMAIL_BACKEND: "anymail.backends.mailgun.EmailBackend"
    K8S_SECRET_DEFAULT_FROM_EMAIL: "venepaikkavaraukset-testi@hel.ninja"
    K8S_SECRET_NOTIFICATIONS_ENABLED: "true"
    K8S_SECRET_SENTRY_DSN: "$GL_QA_SENTRY_DSN"
    K8S_SECRET_SENTRY_ENVIRONMENT: "staging"
    K8S_SECRET_VENE_UI_RETURN_URL: 'https://venepaikka.test.kuva.hel.ninja/{LANG}'
    K8S_SECRET_VENE_UI_URL: "https://venepaikka.test.kuva.hel.ninja"
    K8S_SECRET_VENE_PAYMENTS_BAMBORA_API_URL: "$GL_QA_BAMBORA_API_URL"
    K8S_SECRET_VENE_PAYMENTS_BAMBORA_API_KEY: "$GL_QA_BAMBORA_API_KEY"
    K8S_SECRET_VENE_PAYMENTS_BAMBORA_API_SECRET: "$GL_QA_BAMBORA_API_SECRET"
    K8S_SECRET_VENE_PAYMENTS_BAMBORA_PAYMENT_METHODS: "$GL_QA_BAMBORA_PAYMENT_METHODS"
    K8S_SECRET_PROFILE_API_URL: "https://profiili-api.test.kuva.hel.ninja/graphql/"
    K8S_SECRET_ELASTIC_APM_ENVIRONMENT: "test"
    K8S_SECRET_ELASTIC_APM_SECRET_TOKEN: "$GL_QA_ELASTIC_APM_TOKEN"
    K8S_SECRET_ELASTIC_APM_SERVER_URL: "$GL_QA_ELASTIC_APM_URL"
    K8S_SECRET_ELASTIC_APM_SERVICE_NAME: "berths-backend"
    K8S_SECRET_ENABLE_APM_TOOLS: "$GL_QA_ENABLE_APM_TOOLS"
    K8S_SECRET_VISMASIGN_API_URL: "$GL_TEST_VISMASIGN_API_URL"
    K8S_SECRET_VISMASIGN_CLIENT_IDENTIFIER: "$GL_TEST_VISMASIGN_CLIENT_IDENTIFIER"
    K8S_SECRET_VISMASIGN_SECRET: "$GL_TEST_VISMASIGN_SECRET"
    K8S_SECRET_ENABLE_PROFILING_TOOLS: 1
    K8S_SECRET_NOTIFICATION_SERVICE_API_URL: "http://notification-service-api.test.kuva.hel.ninja/v1"
    K8S_SECRET_NOTIFICATION_SERVICE_SENDER_NAME: "Hel.fi"
    K8S_SECRET_NOTIFICATION_SERVICE_TOKEN: "$GL_QA_NOTIFICATION_SERVICE_TOKEN"

production:
  variables:
    K8S_SECRET_TIER: "prod"
    K8S_SECRET_SKIP_DATABASE_CHECK: 1
    K8S_SECRET_ALLOWED_HOSTS: "*"
    K8S_SECRET_CORS_ORIGIN_ALLOW_ALL: 1
    K8S_SECRET_SECRET_KEY: "$GL_PROD_DJANGO_SECRET_KEY"
    K8S_SECRET_TOKEN_AUTH_AUTHSERVER_URL: "$GL_PROD_SSO_URL"
    K8S_SECRET_MAIL_MAILGUN_KEY: "$GL_PROD_SECRET_MAILGUN_API_KEY"
    K8S_SECRET_MAIL_MAILGUN_DOMAIN: "mail.hel.ninja"
    K8S_SECRET_MAIL_MAILGUN_API: "https://api.eu.mailgun.net/v3"
    K8S_SECRET_MAILER_EMAIL_BACKEND: "anymail.backends.mailgun.EmailBackend"
    K8S_SECRET_DEFAULT_FROM_EMAIL: "venepaikkavaraukset@hel.fi"
    K8S_SECRET_NOTIFICATIONS_ENABLED: "true"
    K8S_SECRET_SENTRY_DSN: "$GL_PROD_SENTRY_DSN"
    K8S_SECRET_SENTRY_ENVIRONMENT: "production"
    K8S_SECRET_VENE_UI_RETURN_URL: 'https://venepaikat.hel.fi/{LANG}'
    K8S_SECRET_VENE_UI_URL: "https://venepaikat.hel.fi"
    K8S_SECRET_VENE_PAYMENTS_BAMBORA_API_URL: "$GL_PROD_BAMBORA_API_URL"
    K8S_SECRET_VENE_PAYMENTS_BAMBORA_API_KEY: "$GL_PROD_BAMBORA_API_KEY"
    K8S_SECRET_VENE_PAYMENTS_BAMBORA_API_SECRET: "$GL_PROD_BAMBORA_API_SECRET"
    K8S_SECRET_VENE_PAYMENTS_BAMBORA_PAYMENT_METHODS: "$GL_PROD_BAMBORA_PAYMENT_METHODS"
    K8S_SECRET_PROFILE_API_URL: "https://profiili-api.prod.kuva.hel.ninja/graphql/"
    K8S_SECRET_ELASTIC_APM_ENVIRONMENT: "production"
    K8S_SECRET_ELASTIC_APM_SECRET_TOKEN: "$GL_PROD_ELASTIC_APM_TOKEN"
    K8S_SECRET_ELASTIC_APM_SERVER_URL: "$GL_PROD_ELASTIC_APM_URL"
    K8S_SECRET_ELASTIC_APM_SERVICE_NAME: "berths-backend"
    K8S_SECRET_FORCE_SCRIPT_NAME: "/berths"
    K8S_SECRET_MEDIA_URL: "/berths/media/"
    K8S_SECRET_STATIC_URL: "/berths/static/"
    K8S_SECRET_CSRF_COOKIE_NAME: "berth-prod-csrftoken"
    K8S_SECRET_CSRF_COOKIE_PATH: "/berths/"
    K8S_SECRET_CSRF_COOKIE_SECURE: 1
    K8S_SECRET_SESSION_COOKIE_NAME: "berth-prod-sessionid"
    K8S_SECRET_SESSION_COOKIE_PATH: "/berths/"
    K8S_SECRET_SESSION_COOKIE_SECURE: 1
    K8S_SECRET_USE_X_FORWARDED_HOST: 1
    K8S_SECRET_CSRF_TRUSTED_ORIGINS: "api.hel.fi"
    K8S_SECRET_FORCED_HOST: "api.hel.fi"
    K8S_SECRET_ENABLE_APM_TOOLS: "$GL_PROD_ENABLE_APM_TOOLS"
    K8S_SECRET_VISMASIGN_API_URL: "$GL_PROD_VISMASIGN_API_URL"
    K8S_SECRET_VISMASIGN_CLIENT_IDENTIFIER: "$GL_PROD_VISMASIGN_CLIENT_IDENTIFIER"
    K8S_SECRET_VISMASIGN_SECRET: "$GL_PROD_VISMASIGN_SECRET"
    K8S_SECRET_ENABLE_PROFILING_TOOLS: 0
    K8S_SECRET_NOTIFICATION_SERVICE_API_URL: "https://api.hel.fi/notification-service/v1"
    K8S_SECRET_NOTIFICATION_SERVICE_SENDER_NAME: "Hel.fi"
    K8S_SECRET_NOTIFICATION_SERVICE_TOKEN: "$GL_PROD_NOTIFICATION_SERVICE_TOKEN"
