dist: xenial

branches: {only: [master, develop]}
sudo: false
language: python
python: "3.6"
cache: pip

addons:
  postgresql: 9.6
  apt:
    packages:
    - postgresql-9.6-postgis-2.4

matrix:
  include:
    - name: Unit tests
      env: DEBUG=1 DATABASE_URL=postgis:///berth_reservations
      services: [postgresql]
      install: pip install -r requirements.txt -r requirements-dev.txt
      before_script:
        - psql -U postgres -c "create extension postgis"
        - createdb berth_reservations
      script: pytest -ra -vv --doctest-modules --cov=.
      after_success: pip install codecov && codecov

    - name: Coding style
      install: pip install -r requirements.txt -r requirements-dev.txt
      script:
        - black --check .
        - flake8
        - isort -c
