#
# Test pipeline. Run build and deploy for Platta test environments. 
# Pipeline runs different tests e.g. unittest and browser tests.
#
# Continuous integration (CI) triggers cause a pipeline to run whenever you push 
# an update to the specified branches or you push specified tags.
trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md
    - CHANGELOG.md

# Pull request (PR) triggers cause a pipeline to run whenever a pull request is 
# opened with one of the specified target branches, or when updates are made to 
# such a pull request.
#
# GitHub creates a new ref when a pull request is created. The ref points to a 
# merge commit, which is the merged code between the source and target branches 
# of the pull request.
#
# Opt out of pull request validation 
pr: none

# By default, use self-hosted agents
pool: Default

resources:
  repositories:
  # Azure DevOps repository
  - repository: venepaikat-pipelines
    type: git
    # Azure DevOps project/repository
    name: venepaikat/venepaikat-pipelines

extends:
  # Filename in Azure DevOps Repository (note possible -ui or -api)
  # Django example: azure-pipelines-PROJECTNAME-api-release.yml
  # Drupal example: azure-pipelines-drupal-release.yml
  template: azure-pipelines-venepaikat-api-test.yml@venepaikat-pipelines
  #parameters:
    #imagetag: ${{ parameters.imagetag }}