version: '3.7'
services:
    postgres:
        build: ./docker/postgres/
        environment:
            POSTGRES_USER: berth_reservations
            POSTGRES_PASSWORD: berth_reservations
            POSTGRES_DB: berth_reservations
        ports:
            - "5432:5432"
        volumes:
            - berth-postgres-data-volume:/var/lib/postgresql/data
        container_name: berth-db

    django:
        build:
            context: ./
        env_file:
            - ./.env
        environment:
            DEV_SERVER: 1
            DATABASE_URL: postgres://berth_reservations:berth_reservations@berth-db/berth_reservations
            DATABASE_HOST: berth-db.helsinki
        volumes:
            - .:/app
            - berth-django-media-volume:/var/media/
        ports:
            - "8000:8000"
        depends_on:
            - postgres
        container_name: berth

volumes:
        berth-postgres-data-volume:
        berth-django-media-volume:

networks:
    default:
        name: helsinki
