TALPA_ECOM_WEBHOOK_EVENT_PAYMENT_PAID = "PAYMENT_PAID"
TALPA_ECOM_WEBHOOK_EVENT_ORDER_CANCELLED = "ORDER_CANCELLED"

TALPA_ECOM_WEBHOOK_EVENT_TYPES = (
    TALPA_ECOM_WEBHOOK_EVENT_PAYMENT_PAID,
    TALPA_ECOM_WEBHOOK_EVENT_ORDER_CANCELLED,
)
