# Generated by Django 2.1.2 on 2019-01-29 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_allow_decimal_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'permissions': (('resend_reservation', 'Can resend confirmation for reservations'),)},
        ),
    ]
