# Generated by Django 2.1.2 on 2019-04-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("reservations", "0005_add_custom_permissions")]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="application_code",
            field=models.TextField(blank=True, verbose_name="application code"),
        )
    ]
