# Generated by Django 2.1.2 on 2019-04-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_add_berth_switch'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='comment',
            field=models.TextField(blank=True, verbose_name='comment'),
        ),
    ]
