# Generated by Django 2.2.6 on 2020-01-09 13:11

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_add_boat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boat",
            name="draught",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="draught (m)",
            ),
        ),
        migrations.AlterField(
            model_name="boat",
            name="length",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="length (m)",
            ),
        ),
        migrations.AlterField(
            model_name="boat",
            name="width",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="width (m)",
            ),
        ),
    ]
