# Generated by Django 2.2.6 on 2020-02-20 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0004_change_boat_weight_to_int"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="boat",
            options={
                "ordering": ("owner",),
                "verbose_name": "boat",
                "verbose_name_plural": "boats",
            },
        ),
        migrations.AlterModelOptions(
            name="customerprofile",
            options={
                "ordering": ("id",),
                "verbose_name": "customer profile",
                "verbose_name_plural": "customer profiles",
            },
        ),
    ]
