# Generated by Django 2.2.6 on 2020-02-20 19:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0005_add_meta_to_profile_and_boats"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="time modified"),
                ),
                (
                    "business_id",
                    models.CharField(max_length=32, verbose_name="business id"),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=128, verbose_name="name"),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="address"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=5, verbose_name="postal code"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=64, verbose_name="city"),
                ),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company",
                        to="customers.CustomerProfile",
                        verbose_name="customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "company",
                "verbose_name_plural": "companies",
                "ordering": ("id",),
            },
        ),
    ]
