# Generated by Django 2.2.6 on 2020-02-26 09:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0006_add_companies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerprofile",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
