# Generated by Django 2.2.6 on 2020-02-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0007_make_customer_profile_id_editable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerprofile",
            name="invoicing_type",
            field=models.CharField(
                choices=[
                    ("online-payment", "Online payment"),
                    ("digital-invoice", "Digital invoice"),
                    ("paper-invoice", "Paper invoice"),
                ],
                default="online-payment",
                max_length=30,
                verbose_name="invoicing type",
            ),
        ),
    ]
