# Generated by Django 2.2.6 on 2020-02-26 09:43

import customers.enums
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0007_make_customer_profile_id_editable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerprofile",
            name="invoicing_type",
            field=enumfields.fields.EnumField(
                default="online-payment",
                enum=customers.enums.InvoicingType,
                max_length=30,
                verbose_name="invoicing type",
            ),
        ),
    ]
