# Generated by Django 2.2.6 on 2020-04-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0009_rename_company_to_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="organization_type",
            field=models.CharField(
                choices=[
                    ("company", "Company"),
                    ("internal", "Internal"),
                    ("non-billable", "Non-billable"),
                    ("other", "Other"),
                ],
                default="company",
                max_length=16,
                verbose_name="organization type",
            ),
            preserve_default=False,
        ),
    ]
