# Generated by Django 2.2.6 on 2020-04-24 08:25

import customers.enums
import customers.models
import django.core.files.storage
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0011_add_intended_use_to_boat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="boat",
            name="boat_is_inspected",
        ),
        migrations.RemoveField(
            model_name="boat",
            name="boat_is_insured",
        ),
        migrations.CreateModel(
            name="BoatCertificate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=django.core.files.storage.FileSystemStorage(),
                        upload_to=customers.models.get_boat_media_folder,
                        verbose_name="certificate file",
                    ),
                ),
                (
                    "certificate_type",
                    models.CharField(
                        choices=[
                            ("inspection", "Inspection"),
                            ("insurance", "Insurance"),
                        ],
                        max_length=16,
                        verbose_name="certificate type",
                    ),
                ),
                (
                    "valid_until",
                    models.DateField(blank=True, null=True, verbose_name="valid until"),
                ),
                (
                    "checked_at",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="checked at"
                    ),
                ),
                (
                    "checked_by",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="checked by"
                    ),
                ),
                (
                    "boat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="customers.Boat",
                        verbose_name="boat",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="boatcertificate",
            constraint=models.UniqueConstraint(
                fields=("boat_id", "certificate_type"), name="unique_boat_certificate"
            ),
        ),
    ]
