# Generated by Django 2.2.6 on 2020-07-03 11:40

import customers.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0012_add_boat_certificates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boatcertificate",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to=customers.models.get_boat_certificate_media_folder,
                verbose_name="certificate file",
            ),
        ),
    ]
