# Generated by Django 3.2.8 on 2021-11-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0015_add_customer_user_relatedname"),
    ]

    operations = [
        migrations.AddField(
            model_name="boat",
            name="is_inspected",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="is inspected"
            ),
        ),
        migrations.AddField(
            model_name="boat",
            name="is_insured",
            field=models.BooleanField(blank=True, null=True, verbose_name="is insured"),
        ),
    ]
