# Generated by Django 3.2.8 on 2021-11-17 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0016_add_boat_is_inspected_and_is_insured"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boat",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boats",
                to="customers.customerprofile",
                verbose_name="owner",
            ),
        ),
    ]
