# Generated by Django 2.1.2 on 2018-11-08 13:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("harbors", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="harbor",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326, verbose_name="Location"
            ),
        ),
        migrations.AlterField(
            model_name="harbor",
            name="suitable_boat_types",
            field=models.ManyToManyField(
                blank=True,
                related_name="harbors",
                to="harbors.BoatType",
                verbose_name="Suitable boat types",
            ),
        ),
        migrations.AlterField(
            model_name="harbortranslation",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Name of the harbor",
                max_length=200,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="harbortranslation",
            name="street_address",
            field=models.CharField(
                blank=True,
                help_text="Street address of the harbor",
                max_length=200,
                verbose_name="street address",
            ),
        ),
    ]
