# Generated by Django 2.1.7 on 2019-04-24 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("harbors", "0007_add_winter_storage_places")]

    operations = [
        migrations.AddField(
            model_name="winterstoragearea",
            name="availability_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="winter_storage_areas",
                to="harbors.AvailabilityLevel",
                verbose_name="Availability level",
            ),
        )
    ]
