# Generated by Django 2.2 on 2019-05-20 08:16

from django.db import migrations


class Migration(migrations.Migration):
    """
    A workaround for a bug in Django: https://code.djangoproject.com/ticket/25105

    Some fields previously were saved as NULL, whereas now we
    want them to not be nullable. Django's AlterField does not
    work 100 % in this case (see link above), especially
    when there are multiple fields that need to be changed.
    """

    dependencies = [("harbors", "0008_add_avlblty_lvl_to_winter_areas")]

    operations = [
        migrations.RunSQL(
            "UPDATE harbors_winterstoragearea "
            "SET zip_code = '' WHERE zip_code is NULL;"
            "UPDATE harbors_winterstoragearea "
            "SET phone = '' WHERE phone is NULL;"
            "UPDATE harbors_winterstoragearea "
            "SET email = '' WHERE email is NULL;"
            "UPDATE harbors_winterstoragearea "
            "SET www_url = '' WHERE www_url is NULL;"
            "UPDATE harbors_winterstoragearea "
            "SET image_link = '' WHERE image_link is NULL;"
            "UPDATE harbors_harbor "
            "SET zip_code = '' WHERE zip_code is NULL;"
            "UPDATE harbors_harbor "
            "SET phone = '' WHERE phone is NULL;"
            "UPDATE harbors_harbor "
            "SET email = '' WHERE email is NULL;"
            "UPDATE harbors_harbor "
            "SET www_url = '' WHERE www_url is NULL;"
            "UPDATE harbors_harbor "
            "SET image_link = '' WHERE image_link is NULL;"
        )
    ]
