# Generated by Django 2.2.5 on 2019-10-04 09:23

from django.db import migrations, models
import django.db.models.deletion
import parler.fields


class Migration(migrations.Migration):

    dependencies = [("harbors", "0010_update_nullable_fields")]

    operations = [
        migrations.AddField(
            model_name="harbor",
            name="disabled",
            field=models.BooleanField(default=False, verbose_name="Disabled"),
        ),
        migrations.AddField(
            model_name="winterstoragearea",
            name="disabled",
            field=models.BooleanField(default=False, verbose_name="Disabled"),
        ),
    ]
