# Generated by Django 3.0.8 on 2020-07-29 13:18

from django.db import migrations
import django.db.models.deletion
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ("harbors", "0012_disable_reverse_from_municipality"),
    ]

    operations = [
        migrations.AlterField(
            model_name="availabilityleveltranslation",
            name="master",
            field=parler.fields.TranslationsForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="harbors.AvailabilityLevel",
            ),
        ),
        migrations.AlterField(
            model_name="boattypetranslation",
            name="master",
            field=parler.fields.TranslationsForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="harbors.BoatType",
            ),
        ),
        migrations.AlterField(
            model_name="harbortranslation",
            name="master",
            field=parler.fields.TranslationsForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="harbors.Harbor",
            ),
        ),
        migrations.AlterField(
            model_name="winterstorageareatranslation",
            name="master",
            field=parler.fields.TranslationsForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="harbors.WinterStorageArea",
            ),
        ),
    ]
