# Generated by Django 3.1 on 2020-09-16 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0019_add_region_field_to_abstract_area"),
        ("harbors", "0013_update_translation_foreign_keys"),
    ]

    operations = [
        migrations.AddField(
            model_name="winterstoragearea",
            name="resources_area",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="harbors_area",
                to="resources.winterstoragearea",
            ),
        ),
    ]
