# Generated by Django 2.2.6 on 2020-01-13 08:49

from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import leases.enums
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0004_change_boat_weight_to_int"),
        ("resources", "0002_add_berth_comments"),
        ("applications", "0014_update_verbose_names"),
    ]

    operations = [
        migrations.CreateModel(
            name="BerthLease",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="time modified"),
                ),
                (
                    "status",
                    enumfields.fields.EnumField(
                        default="offered",
                        enum=leases.enums.LeaseStatus,
                        max_length=30,
                        verbose_name="lease status",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="start date")),
                ("end_date", models.DateField(verbose_name="end date")),
                ("comment", models.TextField(blank=True, verbose_name="comment")),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leases",
                        to="applications.BerthReservation",
                        verbose_name="application",
                    ),
                ),
                (
                    "berth",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leases",
                        to="resources.Berth",
                        verbose_name="berth",
                    ),
                ),
                (
                    "boat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="berth_leases",
                        to="customers.Boat",
                        verbose_name="customer's boat",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="berth_leases",
                        to="customers.CustomerProfile",
                        verbose_name="customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "berth lease",
                "verbose_name_plural": "berth leases",
                "default_related_name": "berth_leases",
            },
        ),
        migrations.CreateModel(
            name="WinterStorageLease",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="time modified"),
                ),
                (
                    "status",
                    enumfields.fields.EnumField(
                        default="offered",
                        enum=leases.enums.LeaseStatus,
                        max_length=30,
                        verbose_name="lease status",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="start date")),
                ("end_date", models.DateField(verbose_name="end date")),
                ("comment", models.TextField(blank=True, verbose_name="comment")),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leases",
                        to="applications.WinterStorageReservation",
                        verbose_name="application",
                    ),
                ),
                (
                    "boat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="winter_storage_leases",
                        to="customers.Boat",
                        verbose_name="customer's boat",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="winter_storage_leases",
                        to="customers.CustomerProfile",
                        verbose_name="customer",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leases",
                        to="resources.WinterStoragePlace",
                        verbose_name="place",
                    ),
                ),
            ],
            options={
                "verbose_name": "winter storage lease",
                "verbose_name_plural": "winter storage leases",
                "default_related_name": "winter_storage_leases",
            },
        ),
        migrations.CreateModel(
            name="WinterStorageLeaseChange",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="time created"
                    ),
                ),
                (
                    "from_status",
                    enumfields.fields.EnumField(
                        enum=leases.enums.LeaseStatus,
                        max_length=30,
                        verbose_name="from status",
                    ),
                ),
                (
                    "to_status",
                    enumfields.fields.EnumField(
                        enum=leases.enums.LeaseStatus,
                        max_length=30,
                        verbose_name="to status",
                    ),
                ),
                (
                    "lease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changes",
                        to="leases.WinterStorageLease",
                        verbose_name="lease",
                    ),
                ),
            ],
            options={
                "verbose_name": "winter storage lease change",
                "verbose_name_plural": "winter storage lease changes",
            },
        ),
        migrations.CreateModel(
            name="BerthLeaseChange",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="time created"
                    ),
                ),
                (
                    "from_status",
                    enumfields.fields.EnumField(
                        enum=leases.enums.LeaseStatus,
                        max_length=30,
                        verbose_name="from status",
                    ),
                ),
                (
                    "to_status",
                    enumfields.fields.EnumField(
                        enum=leases.enums.LeaseStatus,
                        max_length=30,
                        verbose_name="to status",
                    ),
                ),
                (
                    "lease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changes",
                        to="leases.BerthLease",
                        verbose_name="lease",
                    ),
                ),
            ],
            options={
                "verbose_name": "berth lease change",
                "verbose_name_plural": "berth lease changes",
            },
        ),
    ]
