# Generated by Django 2.2.6 on 2020-02-04 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("leases", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="berthlease",
            name="application",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lease",
                to="applications.BerthApplication",
                verbose_name="application",
            ),
        ),
        migrations.AlterField(
            model_name="winterstoragelease",
            name="application",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lease",
                to="applications.WinterStorageApplication",
                verbose_name="application",
            ),
        ),
    ]
