# Generated by Django 2.2.6 on 2020-02-20 11:51

from django.db import migrations
import enumfields.fields
import leases.enums


class Migration(migrations.Migration):

    dependencies = [
        ("leases", "0002_make_applications_one_to_one"),
    ]

    operations = [
        migrations.AlterField(
            model_name="berthlease",
            name="status",
            field=enumfields.fields.EnumField(
                default="drafted",
                enum=leases.enums.LeaseStatus,
                max_length=30,
                verbose_name="lease status",
            ),
        ),
        migrations.AlterField(
            model_name="winterstoragelease",
            name="status",
            field=enumfields.fields.EnumField(
                default="drafted",
                enum=leases.enums.LeaseStatus,
                max_length=30,
                verbose_name="lease status",
            ),
        ),
    ]
