# Generated by Django 2.2.6 on 2020-02-20 13:01

from django.db import migrations, models
import leases.models


class Migration(migrations.Migration):

    dependencies = [
        ("leases", "0003_add_drafted_status_and_set_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="berthlease",
            name="end_date",
            field=models.DateField(
                default=leases.models.calculate_berth_lease_end_date,
                verbose_name="end date",
            ),
        ),
        migrations.AlterField(
            model_name="berthlease",
            name="start_date",
            field=models.DateField(
                default=leases.models.calculate_berth_lease_start_date,
                verbose_name="start date",
            ),
        ),
    ]
