# Generated by Django 2.2.6 on 2020-02-21 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("leases", "0004_calculate_default_dates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="berthlease",
            name="boat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="berth_leases",
                to="customers.Boat",
                verbose_name="customer's boat",
            ),
        ),
        migrations.AlterField(
            model_name="winterstoragelease",
            name="boat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="winter_storage_leases",
                to="customers.Boat",
                verbose_name="customer's boat",
            ),
        ),
    ]
