# Generated by Django 2.2.6 on 2020-04-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leases", "0005_make_boat_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="berthlease",
            name="renew_automatically",
            field=models.BooleanField(default=True, verbose_name="renew automatically"),
        ),
    ]
