# Generated by Django 3.0.8 on 2020-08-03 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("leases", "0007_add_default_winter_season_dates"),
    ]

    operations = [
        migrations.AddField(
            model_name="winterstoragelease",
            name="area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="leases",
                to="resources.WinterStorageArea",
                verbose_name="area",
            ),
        ),
        migrations.AlterField(
            model_name="winterstoragelease",
            name="place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="leases",
                to="resources.WinterStoragePlace",
                verbose_name="place",
            ),
        ),
    ]
