# Generated by Django 3.1 on 2020-09-03 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0018_update_translation_foreign_keys"),
        ("leases", "0008_add_optional_area_to_ws_lease"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="winterstoragelease",
            name="area",
        ),
        migrations.AddField(
            model_name="winterstoragelease",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="leases",
                to="resources.winterstoragesection",
                verbose_name="section",
            ),
        ),
    ]
