# Generated by Django 3.1 on 2020-10-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leases", "0009_attach_lease_to_winter_storage_section"),
    ]

    operations = [
        migrations.AddField(
            model_name="winterstoragelease",
            name="sticker_number",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="sticker number"
            ),
        ),
    ]
