# Generated by Django 3.1 on 2021-02-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leases", "0012_add_renew_failed_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="berthlease",
            name="status",
            field=models.CharField(
                choices=[
                    ("drafted", "Drafted"),
                    ("offered", "Offered"),
                    ("refused", "Refused"),
                    ("expired", "Expired"),
                    ("error", "Error"),
                    ("paid", "Paid"),
                    ("terminated", "Terminated"),
                ],
                default="drafted",
                max_length=30,
                verbose_name="lease status",
            ),
        ),
        migrations.AlterField(
            model_name="berthleasechange",
            name="from_status",
            field=models.CharField(
                choices=[
                    ("drafted", "Drafted"),
                    ("offered", "Offered"),
                    ("refused", "Refused"),
                    ("expired", "Expired"),
                    ("error", "Error"),
                    ("paid", "Paid"),
                    ("terminated", "Terminated"),
                ],
                max_length=30,
                verbose_name="from status",
            ),
        ),
        migrations.AlterField(
            model_name="berthleasechange",
            name="to_status",
            field=models.CharField(
                choices=[
                    ("drafted", "Drafted"),
                    ("offered", "Offered"),
                    ("refused", "Refused"),
                    ("expired", "Expired"),
                    ("error", "Error"),
                    ("paid", "Paid"),
                    ("terminated", "Terminated"),
                ],
                max_length=30,
                verbose_name="to status",
            ),
        ),
        migrations.AlterField(
            model_name="winterstoragelease",
            name="status",
            field=models.CharField(
                choices=[
                    ("drafted", "Drafted"),
                    ("offered", "Offered"),
                    ("refused", "Refused"),
                    ("expired", "Expired"),
                    ("error", "Error"),
                    ("paid", "Paid"),
                    ("terminated", "Terminated"),
                ],
                default="drafted",
                max_length=30,
                verbose_name="lease status",
            ),
        ),
        migrations.AlterField(
            model_name="winterstorageleasechange",
            name="from_status",
            field=models.CharField(
                choices=[
                    ("drafted", "Drafted"),
                    ("offered", "Offered"),
                    ("refused", "Refused"),
                    ("expired", "Expired"),
                    ("error", "Error"),
                    ("paid", "Paid"),
                    ("terminated", "Terminated"),
                ],
                max_length=30,
                verbose_name="from status",
            ),
        ),
        migrations.AlterField(
            model_name="winterstorageleasechange",
            name="to_status",
            field=models.CharField(
                choices=[
                    ("drafted", "Drafted"),
                    ("offered", "Offered"),
                    ("refused", "Refused"),
                    ("expired", "Expired"),
                    ("error", "Error"),
                    ("paid", "Paid"),
                    ("terminated", "Terminated"),
                ],
                max_length=30,
                verbose_name="to status",
            ),
        ),
    ]
