# Generated by Django 3.1.7 on 2021-04-19 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leases", "0013_add_terminate_status"),
    ]

    operations = [
        migrations.RemoveField(model_name="berthlease", name="renew_automatically",),
    ]
