# Generated by Django 2.2 on 2019-05-09 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("notifications", "0003_add_admin_notifications")]

    operations = [
        migrations.RunSQL(
            # forward
            "UPDATE notifications_notificationtemplate "
            "SET type = 'berth_reservation_created' "
            "WHERE type = 'reservation_created';",
            # reverse
            "UPDATE notifications_notificationtemplate "
            "SET type = 'reservation_created' "
            "WHERE type = 'berth_reservation_created';",
        )
    ]
