# Generated by Django 2.2.6 on 2020-02-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0003_replace_abstractplacetype_units"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="berthtype",
            options={
                "ordering": ("width", "length", "depth"),
                "verbose_name": "berth type",
                "verbose_name_plural": "berth types",
            },
        ),
        migrations.AddField(
            model_name="berthtype",
            name="depth",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="depth (m)",
            ),
        ),
    ]
