# Generated by Django 2.2.6 on 2020-03-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0006_remove_overwrite_storage"),
    ]

    operations = [
        migrations.AddField(
            model_name="berth",
            name="is_accessible",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="is accessible"
            ),
        ),
    ]
