# Generated by Django 2.2.6 on 2020-04-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0008_remove_hard_coded_maximums"),
    ]

    operations = [
        migrations.AlterField(
            model_name="winterstoragearea",
            name="max_length_of_section_spaces",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="maximum length of section spaces",
            ),
        ),
    ]
