# Generated by Django 2.2.6 on 2020-04-02 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0009_max_length_of_section_spaces_as_decimal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="harbor",
            name="number_of_places",
        ),
        migrations.RemoveField(
            model_name="winterstoragearea",
            name="number_of_marked_places",
        ),
    ]
