# Generated by Django 2.2.6 on 2020-04-02 15:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0010_remove_hard_coded_total_places"),
    ]

    operations = [
        migrations.AddField(
            model_name="berth",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="time created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="berth",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, verbose_name="time modified"),
        ),
        migrations.AddField(
            model_name="berthtype",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="time created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="berthtype",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, verbose_name="time modified"),
        ),
        migrations.AddField(
            model_name="harbor",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="time created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="harbor",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, verbose_name="time modified"),
        ),
        migrations.AddField(
            model_name="pier",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="time created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pier",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, verbose_name="time modified"),
        ),
        migrations.AddField(
            model_name="winterstoragearea",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="time created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="winterstoragearea",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, verbose_name="time modified"),
        ),
        migrations.AddField(
            model_name="winterstorageplace",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="time created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="winterstorageplace",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, verbose_name="time modified"),
        ),
        migrations.AddField(
            model_name="winterstorageplacetype",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="time created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="winterstorageplacetype",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, verbose_name="time modified"),
        ),
        migrations.AddField(
            model_name="winterstoragesection",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="time created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="winterstoragesection",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, verbose_name="time modified"),
        ),
    ]
