# Generated by Django 2.2.6 on 2020-04-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0011_add_timestamp_to_resources"),
    ]

    operations = [
        migrations.AddField(
            model_name="berth",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="is active"),
        ),
        migrations.AddField(
            model_name="winterstorageplace",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="is active"),
        ),
    ]
