# Generated by Django 2.2.6 on 2020-04-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0013_add_personal_electricity_option_to_pier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="berth",
            name="number",
            field=models.PositiveSmallIntegerField(verbose_name="number"),
        ),
        migrations.AlterField(
            model_name="winterstorageplace",
            name="number",
            field=models.PositiveSmallIntegerField(verbose_name="number"),
        ),
    ]
