# Generated by Django 2.2.6 on 2020-05-15 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
        ("resources", "0015_add_depth_to_berthtype_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="berthtype",
            name="price_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="berth_types",
                to="payments.BerthPriceGroup",
                verbose_name="price group",
            ),
        ),
    ]
