# Generated by Django 2.2.13 on 2020-07-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0016_add_price_group_to_berthtype"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="winterstoragearea",
            name="number_of_section_spaces",
        ),
        migrations.RemoveField(
            model_name="winterstoragearea",
            name="number_of_unmarked_spaces",
        ),
        migrations.AddField(
            model_name="winterstoragearea",
            name="estimated_number_of_section_spaces",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="estimated number of section places"
            ),
        ),
        migrations.AddField(
            model_name="winterstoragearea",
            name="estimated_number_of_unmarked_spaces",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                verbose_name="estimated number of unmarked places",
            ),
        ),
    ]
