# Generated by Django 3.0.8 on 2020-07-29 13:18

from django.db import migrations
import django.db.models.deletion
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0017_rename_estimated_places_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="availabilityleveltranslation",
            name="master",
            field=parler.fields.TranslationsForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="resources.AvailabilityLevel",
            ),
        ),
        migrations.AlterField(
            model_name="boattypetranslation",
            name="master",
            field=parler.fields.TranslationsForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="resources.BoatType",
            ),
        ),
        migrations.AlterField(
            model_name="harbortranslation",
            name="master",
            field=parler.fields.TranslationsForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="resources.Harbor",
            ),
        ),
        migrations.AlterField(
            model_name="winterstorageareatranslation",
            name="master",
            field=parler.fields.TranslationsForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="resources.WinterStorageArea",
            ),
        ),
    ]
