# Generated by Django 3.1 on 2020-09-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0019_add_region_field_to_abstract_area"),
    ]

    operations = [
        migrations.AlterField(
            model_name="berth",
            name="number",
            field=models.CharField(max_length=30, verbose_name="number"),
        ),
    ]
