# Generated by Django 3.1 on 2020-11-06 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0021_change_image_file_to_char"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="berth",
            options={
                "ordering": ("pier",),
                "verbose_name": "berth",
                "verbose_name_plural": "berths",
            },
        ),
    ]
