# Generated by Django 3.1 on 2020-12-10 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0022_update_berth_ordering"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="harbor",
            name="image_link",
        ),
        migrations.RemoveField(
            model_name="winterstoragearea",
            name="image_link",
        ),
    ]
