# Generated by Django 3.1 on 2020-12-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0024_add_price_tiers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pier",
            name="price_tier",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Tier 1"), (2, "Tier 2"), (3, "Tier 3")],
                default=1,
                verbose_name="price tier",
            ),
        ),
    ]
