# Generated by Django 3.1 on 2021-03-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0025_default_pier_price_tier"),
    ]

    operations = [
        migrations.AddField(
            model_name="berth",
            name="is_invoiceable",
            field=models.BooleanField(default=True, verbose_name="is invoiceable"),
        ),
    ]
