# Generated by Django 3.1 on 2021-03-26 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0028_remove_winter_section_repair_area"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pier",
            name="harbors_harbor",
        ),
    ]
