# Generated by Django 3.1.7 on 2021-04-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0029_remove_pier_harbors_harbor"),
    ]

    operations = [
        migrations.AddField(
            model_name="winterstorageplace",
            name="is_invoiceable",
            field=models.BooleanField(default=True, verbose_name="is invoiceable"),
        ),
    ]
