# Generated by Django 3.1.7 on 2021-04-28 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0030_is_invoiceable_for_abstract_place"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="winterstorageareamap",
            name="winter_storage_area",
        ),
        migrations.DeleteModel(
            name="HarborMap",
        ),
        migrations.DeleteModel(
            name="WinterStorageAreaMap",
        ),
    ]
