name: k6 Load Tests

# Only trigger when the staging workflow succeeded
on:
  workflow_run:
    workflows: ["Build & Staging"]
    types:
      - completed

# allow only one run at a time
concurrency: ${{ github.workflow }}

jobs:
  k6_load_test:
    name: k6 Load Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run k6 tests
        uses: k6io/action@v0.1
        with:
          filename: k6LoadTests.js
      - name: k6 Load Tests failed notifications
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: K6LoadTest
          SLACK_ICON: https://a.slack-edge.com/80588/img/services/outgoing-webhook_48.png
          SLACK_TITLE: K6 Load Tests has failed.
          SLACK_MESSAGE: Some of the k6 load tests has failed.
        if: failure()